### ISSUE TITLE
Why this lib, when exists TextInputLayout

### ISSUE THREAD

**Issue by mtrakal** [bufferapp/CounterView#1]
What improve/new is in this lib against native TextInputLayout?

https://www.journaldev.com/14748/android-textinputlayout-example#character-counter

Thanks

**Comment by hitherejoe** [comment]
This library allows you to display the text count in different ways, such as a descending / ascending count. It also allows you to place the counter in different places in your layout, rather than forcing it to be to the right/bottom of the edittext layout :)
